# Generated by OmopViewer 0.4.0
# Be careful editing this file

library(bslib)
library(dplyr)
library(DT)
library(gt)
library(markdown)
library(omopgenerics)
library(OmopSketch)
library(plotly)
library(purrr)
library(readr)
library(rlang)
library(shiny)
library(shinycssloaders)
library(shinyTree)
library(shinyWidgets)
library(tidyr)
library(visOmopResults)
library(yaml)

# Preprocess data when needed. OmopViewer's generated check only tests whether
# the cache exists, which can silently show results from an older results.csv.
fileData <- file.path(getwd(), "data", "shinyData.RData")
rawDataFiles <- list.files(
  file.path(getwd(), "data"),
  pattern = "\\.(csv|zip)$",
  full.names = TRUE
)
protocolPairsFile <- file.path(getwd(), "data", "analysis_pairs.csv")
if (file.exists(protocolPairsFile)) rawDataFiles <- c(rawDataFiles, protocolPairsFile)
cacheIsStale <- !file.exists(fileData) ||
  (length(rawDataFiles) > 0 &&
    max(file.info(rawDataFiles)$mtime, na.rm = TRUE) >
      file.info(fileData)$mtime)
if (cacheIsStale) {
  source(file.path(getwd(), "data", "preprocess.R"))
}

# uncomment to load the raw data
# rawData <- omopgenerics::importSummarisedResult(file.path(getwd(), "data"))

# load shiny data
load(fileData)

# source functions
source(file.path(getwd(), "functions.R"))
