# Generated by OmopViewer 0.4.0
# Be careful editing this file

server <- function(input, output, session) {
  # summary ----
  output$summary_cdm_name <- shinyTree::renderTree(summaryCdmName(data))
  output$summary_packages <- shinyTree::renderTree(summaryPackages(data))
  output$summary_min_cell_count <- shinyTree::renderTree(summaryMinCellCount(data))
  output$summary_panels <- shinyTree::renderTree(summaryPanels(data))
  # download raw data -----
  output$download_raw <- shiny::downloadHandler(
    filename = "results.csv",
    content = function(file) {
      data |>
        omopgenerics::bind() |>
        omopgenerics::exportSummarisedResult(fileName = file)
    }
  )
  # update buttons ----
  updateButtons <- shiny::reactiveValues(
    summarise_omop_snapshot = FALSE,
    summarise_log_file = FALSE,
    sequence_ratios = FALSE,
    temporal_symmetry = FALSE
  )

  # summarise_omop_snapshot -----
  ## update message if filter is changed
  shiny::observeEvent(input$summarise_omop_snapshot_cdm_name,
    {
      updateButtons$summarise_omop_snapshot <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_omop_snapshot_variable_name,
    {
      updateButtons$summarise_omop_snapshot <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_omop_snapshot, {
    if (updateButtons$summarise_omop_snapshot == TRUE) {
      output$update_message_summarise_omop_snapshot <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_summarise_omop_snapshot <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_summarise_omop_snapshot, {
    updateButtons$summarise_omop_snapshot <- FALSE
  })

  ## get summarise_omop_snapshot data
  getSummariseOmopSnapshotData <- shiny::eventReactive(input$update_summarise_omop_snapshot, {
    data[["summarise_omop_snapshot"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_omop_snapshot_cdm_name,
        .data$variable_name %in% input$summarise_omop_snapshot_variable_name
      )
  })
  getSummariseOmopSnapshotTidy <- shiny::reactive({
    tidyDT(getSummariseOmopSnapshotData(), input$summarise_omop_snapshot_tidy_columns, input$summarise_omop_snapshot_tidy_pivot_estimates)
  })
  output$summarise_omop_snapshot_tidy <- DT::renderDT({
    getSummariseOmopSnapshotTidy()
  })
  output$summarise_omop_snapshot_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseOmopSnapshotData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseOmopSnapshotTable <- shiny::reactive({
    getSummariseOmopSnapshotData() |>
      OmopSketch::tableOmopSnapshot()
  })
  output$summarise_omop_snapshot_table <- gt::render_gt({
    getSummariseOmopSnapshotTable()
  })
  output$summarise_omop_snapshot_table_download <- shiny::downloadHandler(
    filename = paste0("table_snapshot.", input$summarise_omop_snapshot_table_format),
    content = function(file) {
      gt::gtsave(getSummariseOmopSnapshotTable(), file)
    }
  )
  # summarise_log_file -----
  ## update message if filter is changed
  shiny::observeEvent(input$summarise_log_file_cdm_name,
    {
      updateButtons$summarise_log_file <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_log_file_log_id,
    {
      updateButtons$summarise_log_file <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_log_file_variable_name,
    {
      updateButtons$summarise_log_file <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$summarise_log_file_estimate_name,
    {
      updateButtons$summarise_log_file <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$summarise_log_file, {
    if (updateButtons$summarise_log_file == TRUE) {
      output$update_message_summarise_log_file <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_summarise_log_file <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_summarise_log_file, {
    updateButtons$summarise_log_file <- FALSE
  })

  ## get summarise_log_file data
  getSummariseLogFileData <- shiny::eventReactive(input$update_summarise_log_file, {
    data[["summarise_log_file"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$summarise_log_file_cdm_name,
        .data$variable_name %in% input$summarise_log_file_variable_name,
        .data$estimate_name %in% input$summarise_log_file_estimate_name
      ) |>
      omopgenerics::filterStrata(.data$log_id %in% input$summarise_log_file_log_id)
  })
  getSummariseLogFileTidy <- shiny::reactive({
    tidyDT(getSummariseLogFileData(), input$summarise_log_file_tidy_columns, input$summarise_log_file_tidy_pivot_estimates)
  })
  output$summarise_log_file_tidy <- DT::renderDT({
    getSummariseLogFileTidy()
  })
  output$summarise_log_file_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSummariseLogFileData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSummariseLogFileTable <- shiny::reactive({
    getSummariseLogFileData() |>
      simpleTable(
        header = input$summarise_log_file_table_header,
        group = input$summarise_log_file_table_group_column,
        hide = input$summarise_log_file_table_hide
      )
  })
  output$summarise_log_file_table <- gt::render_gt({
    getSummariseLogFileTable()
  })
  output$summarise_log_file_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$summarise_log_file_table_format),
    content = function(file) {
      gt::gtsave(getSummariseLogFileTable(), file)
    }
  )
  # sequence_ratios -----
  ## update message if filter is changed
  shiny::observeEvent(input$sequence_ratios_cdm_name,
    {
      updateButtons$sequence_ratios <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$sequence_ratios_index_cohort_name,
    {
      updateButtons$sequence_ratios <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$sequence_ratios_marker_cohort_name,
    {
      updateButtons$sequence_ratios <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$sequence_ratios_variable_name,
    {
      updateButtons$sequence_ratios <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$sequence_ratios_estimate_name,
    {
      updateButtons$sequence_ratios <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$sequence_ratios_cdm_name,
    {
      updateButtons$sequence_ratios <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$sequence_ratios_cohort_date_range,
    {
      updateButtons$sequence_ratios <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$sequence_ratios_combination_window,
    {
      updateButtons$sequence_ratios <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$sequence_ratios_confidence_interval,
    {
      updateButtons$sequence_ratios <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$sequence_ratios_days_prior_observation,
    {
      updateButtons$sequence_ratios <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$sequence_ratios_index_marker_gap,
    {
      updateButtons$sequence_ratios <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$sequence_ratios_moving_average_restriction,
    {
      updateButtons$sequence_ratios <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(input$sequence_ratios_washout_window,
    {
      updateButtons$sequence_ratios <- TRUE
    },
    ignoreInit = TRUE
  )
  shiny::observeEvent(updateButtons$sequence_ratios, {
    if (updateButtons$sequence_ratios == TRUE) {
      output$update_message_sequence_ratios <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_sequence_ratios <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_sequence_ratios, {
    updateButtons$sequence_ratios <- FALSE
  })

  ## get sequence_ratios data
  getSequenceRatiosData <- shiny::eventReactive(input$update_sequence_ratios, {
    data[["sequence_ratios"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$sequence_ratios_cdm_name,
        .data$variable_name %in% input$sequence_ratios_variable_name,
        .data$estimate_name %in% input$sequence_ratios_estimate_name
      ) |>
      omopgenerics::filterGroup(
        .data$index_cohort_name %in% input$sequence_ratios_index_cohort_name,
        .data$marker_cohort_name %in% input$sequence_ratios_marker_cohort_name
      ) |>
      omopgenerics::filterSettings(
        .data$cdm_name %in% input$sequence_ratios_cdm_name,
        .data$cohort_date_range %in% input$sequence_ratios_cohort_date_range,
        .data$combination_window %in% input$sequence_ratios_combination_window,
        .data$confidence_interval %in% input$sequence_ratios_confidence_interval,
        .data$days_prior_observation %in% input$sequence_ratios_days_prior_observation,
        .data$index_marker_gap %in% input$sequence_ratios_index_marker_gap,
        .data$moving_average_restriction %in% input$sequence_ratios_moving_average_restriction,
        .data$washout_window %in% input$sequence_ratios_washout_window
      )
  })
  getSequenceRatiosTidy <- shiny::reactive({
    tidyDT(getSequenceRatiosData(), input$sequence_ratios_tidy_columns, input$sequence_ratios_tidy_pivot_estimates)
  })
  output$sequence_ratios_tidy <- DT::renderDT({
    getSequenceRatiosTidy()
  })
  output$sequence_ratios_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getSequenceRatiosData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getSequenceRatiosTable <- shiny::reactive({
    getSequenceRatiosData() |>
      cohortSymmetryTable(
        header = input$sequence_ratios_table_header,
        group = input$sequence_ratios_table_group_column,
        hide = input$sequence_ratios_table_hide
      )
  })
  output$sequence_ratios_table <- gt::render_gt({
    getSequenceRatiosTable()
  })
  output$sequence_ratios_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$sequence_ratios_table_format),
    content = function(file) {
      gt::gtsave(getSequenceRatiosTable(), file)
    }
  )
  getSequenceRatiosPlot <- shiny::reactive({
    getSequenceRatiosData() |>
      cohortSymmetryPlot(
        x = input$sequence_ratios_plot_x,
        facet = input$sequence_ratios_plot_facet,
        colour = input$sequence_ratios_plot_colour
      )
  })
  output$sequence_ratios_plot <- plotly::renderPlotly({
    plot <- getSequenceRatiosPlot()
    if (inherits(plot, "ggplot")) {
      plotly::ggplotly(plot)
    } else {
      plot
    }
  })
  output$sequence_ratios_plot_download <- shiny::downloadHandler(
    filename = "plot_sequence_ratios.html",
    content = function(file) {
      plot <- getSequenceRatiosPlot()
      if (inherits(plot, "ggplot")) {
        plot <- plotly::ggplotly(plot)
      }
      htmlwidgets::saveWidget(plot, file = file, selfcontained = TRUE)
    }
  )

  # temporal_symmetry -----
  ## update message if filter is changed
  shiny::observeEvent(input$temporal_symmetry_cdm_name, {
    updateButtons$temporal_symmetry <- TRUE
  }, ignoreInit = TRUE)
  shiny::observeEvent(input$temporal_symmetry_index_name, {
    updateButtons$temporal_symmetry <- TRUE
  }, ignoreInit = TRUE)
  shiny::observeEvent(input$temporal_symmetry_marker_name, {
    updateButtons$temporal_symmetry <- TRUE
  }, ignoreInit = TRUE)
  shiny::observeEvent(input$temporal_symmetry_variable_name, {
    updateButtons$temporal_symmetry <- TRUE
  }, ignoreInit = TRUE)
  shiny::observeEvent(input$temporal_symmetry_estimate_name, {
    updateButtons$temporal_symmetry <- TRUE
  }, ignoreInit = TRUE)
  shiny::observeEvent(input$temporal_symmetry_cohort_date_range, {
    updateButtons$temporal_symmetry <- TRUE
  }, ignoreInit = TRUE)
  shiny::observeEvent(input$temporal_symmetry_combination_window, {
    updateButtons$temporal_symmetry <- TRUE
  }, ignoreInit = TRUE)
  shiny::observeEvent(input$temporal_symmetry_days_prior_observation, {
    updateButtons$temporal_symmetry <- TRUE
  }, ignoreInit = TRUE)
  shiny::observeEvent(input$temporal_symmetry_index_marker_gap, {
    updateButtons$temporal_symmetry <- TRUE
  }, ignoreInit = TRUE)
  shiny::observeEvent(input$temporal_symmetry_moving_average_restriction, {
    updateButtons$temporal_symmetry <- TRUE
  }, ignoreInit = TRUE)
  shiny::observeEvent(input$temporal_symmetry_timescale, {
    updateButtons$temporal_symmetry <- TRUE
  }, ignoreInit = TRUE)
  shiny::observeEvent(input$temporal_symmetry_washout_window, {
    updateButtons$temporal_symmetry <- TRUE
  }, ignoreInit = TRUE)
  shiny::observeEvent(updateButtons$temporal_symmetry, {
    if (updateButtons$temporal_symmetry == TRUE) {
      output$update_message_temporal_symmetry <- shiny::renderText("Filters have changed please consider to use the update content button!")
    } else {
      output$update_message_temporal_symmetry <- shiny::renderText("")
    }
  })
  shiny::observeEvent(input$update_temporal_symmetry, {
    updateButtons$temporal_symmetry <- FALSE
  })

  ## get temporal_symmetry data
  getTemporalSymmetryData <- shiny::eventReactive(input$update_temporal_symmetry, {
    data[["temporal_symmetry"]] |>
      dplyr::filter(
        .data$cdm_name %in% input$temporal_symmetry_cdm_name,
        .data$variable_name %in% input$temporal_symmetry_variable_name,
        .data$estimate_name %in% input$temporal_symmetry_estimate_name
      ) |>
      omopgenerics::filterGroup(
        .data$index_name %in% input$temporal_symmetry_index_name,
        .data$marker_name %in% input$temporal_symmetry_marker_name
      ) |>
      omopgenerics::filterSettings(
        .data$cdm_name %in% input$temporal_symmetry_cdm_name,
        .data$cohort_date_range %in% input$temporal_symmetry_cohort_date_range,
        .data$combination_window %in% input$temporal_symmetry_combination_window,
        .data$days_prior_observation %in% input$temporal_symmetry_days_prior_observation,
        .data$index_marker_gap %in% input$temporal_symmetry_index_marker_gap,
        .data$moving_average_restriction %in% input$temporal_symmetry_moving_average_restriction,
        .data$timescale %in% input$temporal_symmetry_timescale,
        .data$washout_window %in% input$temporal_symmetry_washout_window
      )
  })
  getTemporalSymmetryTidy <- shiny::reactive({
    tidyDT(getTemporalSymmetryData(), input$temporal_symmetry_tidy_columns, input$temporal_symmetry_tidy_pivot_estimates)
  })
  output$temporal_symmetry_tidy <- DT::renderDT({
    getTemporalSymmetryTidy()
  })
  output$temporal_symmetry_tidy_download <- shiny::downloadHandler(
    filename = "tidy_results.csv",
    content = function(file) {
      getTemporalSymmetryData() |>
        omopgenerics::tidy() |>
        readr::write_csv(file = file)
    }
  )
  getTemporalSymmetryTable <- shiny::reactive({
    getTemporalSymmetryData() |>
      cohortSymmetryTable(
        header = input$temporal_symmetry_table_header,
        group = input$temporal_symmetry_table_group_column,
        hide = input$temporal_symmetry_table_hide
      )
  })
  output$temporal_symmetry_table <- gt::render_gt({
    getTemporalSymmetryTable()
  })
  output$temporal_symmetry_table_download <- shiny::downloadHandler(
    filename = paste0("table.", input$temporal_symmetry_table_format),
    content = function(file) {
      gt::gtsave(getTemporalSymmetryTable(), file)
    }
  )
  getTemporalSymmetryPlot <- shiny::reactive({
    getTemporalSymmetryData() |>
      cohortSymmetryPlot(
        x = input$temporal_symmetry_plot_x,
        facet = input$temporal_symmetry_plot_facet,
        colour = input$temporal_symmetry_plot_colour
      )
  })
  output$temporal_symmetry_plot <- plotly::renderPlotly({
    plot <- getTemporalSymmetryPlot()
    if (inherits(plot, "ggplot")) {
      plotly::ggplotly(plot)
    } else {
      plot
    }
  })
  output$temporal_symmetry_plot_download <- shiny::downloadHandler(
    filename = "plot_temporal_symmetry.html",
    content = function(file) {
      plot <- getTemporalSymmetryPlot()
      if (inherits(plot, "ggplot")) {
        plot <- plotly::ggplotly(plot)
      }
      htmlwidgets::saveWidget(plot, file = file, selfcontained = TRUE)
    }
  )
}
