# Generated by OmopViewer 0.4.0
# Be careful editing this file

ui <- bslib::page_navbar(
  title = shiny::tags$span(
    shiny::tags$img(
      src = "ohdsi_logo.svg",
      width = "auto",
      height = "46px",
      class = "me-3",
      alt = "logo"
    ),
    ""
  ),
  theme = bslib::bs_theme(bootswatch = "flatly"),
  bslib::nav_panel(
    title = "Background",
    icon = shiny::icon("book-atlas"),
    backgroundCard("background.md")
  ),
  bslib::nav_panel(
    title = "Summary",
    icon = shiny::icon("file-alt"),
    bslib::card(
      bslib::card_header("Explore results"),
      shiny::tags$div(
        class = "mb-2",
        shinyTree::shinyTree("summary_cdm_name", theme = "proton", themeIcons = FALSE),
        shinyTree::shinyTree("summary_packages", theme = "proton", themeIcons = FALSE),
        shinyTree::shinyTree("summary_min_cell_count", theme = "proton", themeIcons = FALSE),
        shinyTree::shinyTree("summary_panels", theme = "proton", themeIcons = FALSE)
      ),
      full_screen = TRUE
    )
  ),
  bslib::nav_menu(
    title = "OmopSketch",
    icon = shiny::icon("list"),
    bslib::nav_panel(
      title = "Snapshot",
      icon = shiny::icon("clipboard-list"),
      bslib::layout_sidebar(
        sidebar = bslib::sidebar(
          shinyWidgets::pickerInput(
            inputId = "summarise_omop_snapshot_cdm_name",
            label = "CDM name",
            choices = choices$summarise_omop_snapshot_cdm_name,
            selected = selected$summarise_omop_snapshot_cdm_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          shinyWidgets::pickerInput(
            inputId = "summarise_omop_snapshot_variable_name",
            label = "Variable name",
            choices = choices$summarise_omop_snapshot_variable_name,
            selected = selected$summarise_omop_snapshot_variable_name,
            multiple = TRUE,
            options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
          ),
          position = "left"
        ),
        shiny::actionButton(
          inputId = "update_summarise_omop_snapshot",
          label = "Update content",
          width = "200px"
        ),
        shiny::div(shiny::textOutput(outputId = "update_message_summarise_omop_snapshot"), class = "ov_update_button"),
        bslib::navset_card_tab(
          bslib::nav_panel(
            title = "Tidy",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shiny::downloadButton(outputId = "summarise_omop_snapshot_tidy_download", label = "Download csv")
                ),
                class = "text-end"
              ),
              bslib::layout_sidebar(
                sidebar = bslib::sidebar(
                  shinyWidgets::pickerInput(
                    inputId = "summarise_omop_snapshot_tidy_columns",
                    label = "Columns",
                    choices = c("cdm_name", "variable_name", "variable_level"),
                    selected = c("cdm_name", "variable_name", "variable_level"),
                    multiple = TRUE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::checkboxInput(
                    inputId = "summarise_omop_snapshot_tidy_pivot_estimates",
                    label = "Pivot estimates",
                    value = TRUE
                  ),
                  position = "right"
                ),
                DT::DTOutput("summarise_omop_snapshot_tidy") |>
                  shinycssloaders::withSpinner()
              )
            )
          ),
          bslib::nav_panel(
            title = "Table Snapshot",
            bslib::card(
              full_screen = TRUE,
              bslib::card_header(
                bslib::popover(
                  shiny::icon("download"),
                  shinyWidgets::pickerInput(
                    inputId = "summarise_omop_snapshot_table_format",
                    label = "Format",
                    choices = c("docx", "png", "pdf", "html"),
                    selected = "docx",
                    multiple = FALSE,
                    options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                  ),
                  shiny::downloadButton(outputId = "summarise_omop_snapshot_table_download", label = "Download table")
                ),
                class = "text-end"
              ),
              gt::gt_output("summarise_omop_snapshot_table") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Summarise log file",
    icon = shiny::icon("folder"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        shinyWidgets::pickerInput(
          inputId = "summarise_log_file_cdm_name",
          label = "CDM name",
          choices = choices$summarise_log_file_cdm_name,
          selected = selected$summarise_log_file_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_log_file_log_id",
          label = "Log id",
          choices = choices$summarise_log_file_log_id,
          selected = selected$summarise_log_file_log_id,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_log_file_variable_name",
          label = "Variable name",
          choices = choices$summarise_log_file_variable_name,
          selected = selected$summarise_log_file_variable_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "summarise_log_file_estimate_name",
          label = "Estimate name",
          choices = choices$summarise_log_file_estimate_name,
          selected = selected$summarise_log_file_estimate_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        position = "left"
      ),
      shiny::actionButton(
        inputId = "update_summarise_log_file",
        label = "Update content",
        width = "200px"
      ),
      shiny::div(shiny::textOutput(outputId = "update_message_summarise_log_file"), class = "ov_update_button"),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "summarise_log_file_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "summarise_log_file_tidy_columns",
                  label = "Columns",
                  choices = c("cdm_name", "log_id", "variable_name", "variable_level"),
                  selected = c("cdm_name", "log_id", "variable_name", "variable_level"),
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::checkboxInput(
                  inputId = "summarise_log_file_tidy_pivot_estimates",
                  label = "Pivot estimates",
                  value = TRUE
                ),
                position = "right"
              ),
              DT::DTOutput("summarise_log_file_tidy") |>
                shinycssloaders::withSpinner()
            )
          )
        ),
        bslib::nav_panel(
          title = "Table",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "summarise_log_file_table_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "summarise_log_file_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                sortable::bucket_list(
                  header = NULL,
                  sortable::add_rank_list(
                    text = "None",
                    labels = c("cdm_name", "log_id", "variable_name", "variable_level", "estimate_name"),
                    input_id = "summarise_log_file_table_none"
                  ),
                  sortable::add_rank_list(
                    text = "Header",
                    labels = character(),
                    input_id = "summarise_log_file_table_header"
                  ),
                  sortable::add_rank_list(
                    text = "Group columns",
                    labels = character(),
                    input_id = "summarise_log_file_table_group_column"
                  ),
                  sortable::add_rank_list(
                    text = "Hide",
                    labels = character(),
                    input_id = "summarise_log_file_table_hide"
                  )
                ),
                position = "right"
              ),
              gt::gt_output("summarise_log_file_table") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Sequence ratios",
    icon = shiny::icon("folder"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        shinyWidgets::pickerInput(
          inputId = "sequence_ratios_cdm_name",
          label = "CDM name",
          choices = choices$sequence_ratios_cdm_name,
          selected = selected$sequence_ratios_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "sequence_ratios_index_cohort_name",
          label = "Index cohort name",
          choices = choices$sequence_ratios_index_cohort_name,
          selected = selected$sequence_ratios_index_cohort_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "sequence_ratios_marker_cohort_name",
          label = "Marker cohort name",
          choices = choices$sequence_ratios_marker_cohort_name,
          selected = selected$sequence_ratios_marker_cohort_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "sequence_ratios_variable_name",
          label = "Variable name",
          choices = choices$sequence_ratios_variable_name,
          selected = selected$sequence_ratios_variable_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "sequence_ratios_estimate_name",
          label = "Estimate name",
          choices = choices$sequence_ratios_estimate_name,
          selected = selected$sequence_ratios_estimate_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "sequence_ratios_cdm_name",
          label = "Cdm name",
          choices = choices$sequence_ratios_cdm_name,
          selected = selected$sequence_ratios_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "sequence_ratios_cohort_date_range",
          label = "Cohort date range",
          choices = choices$sequence_ratios_cohort_date_range,
          selected = selected$sequence_ratios_cohort_date_range,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "sequence_ratios_combination_window",
          label = "Combination window",
          choices = choices$sequence_ratios_combination_window,
          selected = selected$sequence_ratios_combination_window,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "sequence_ratios_confidence_interval",
          label = "Confidence interval",
          choices = choices$sequence_ratios_confidence_interval,
          selected = selected$sequence_ratios_confidence_interval,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "sequence_ratios_days_prior_observation",
          label = "Days prior observation",
          choices = choices$sequence_ratios_days_prior_observation,
          selected = selected$sequence_ratios_days_prior_observation,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "sequence_ratios_index_marker_gap",
          label = "Index marker gap",
          choices = choices$sequence_ratios_index_marker_gap,
          selected = selected$sequence_ratios_index_marker_gap,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "sequence_ratios_moving_average_restriction",
          label = "Moving average restriction",
          choices = choices$sequence_ratios_moving_average_restriction,
          selected = selected$sequence_ratios_moving_average_restriction,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "sequence_ratios_washout_window",
          label = "Washout window",
          choices = choices$sequence_ratios_washout_window,
          selected = selected$sequence_ratios_washout_window,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        position = "left"
      ),
      shiny::actionButton(
        inputId = "update_sequence_ratios",
        label = "Update content",
        width = "200px"
      ),
      shiny::div(shiny::textOutput(outputId = "update_message_sequence_ratios"), class = "ov_update_button"),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "sequence_ratios_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "sequence_ratios_tidy_columns",
                  label = "Columns",
                  choices = c("cdm_name", "index_cohort_name", "marker_cohort_name", "cdm_name", "cohort_date_range", "combination_window", "confidence_interval", "days_prior_observation", "index_marker_gap", "moving_average_restriction", "washout_window", "variable_name", "variable_level"),
                  selected = c("cdm_name", "index_cohort_name", "marker_cohort_name", "variable_name", "variable_level"),
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::checkboxInput(
                  inputId = "sequence_ratios_tidy_pivot_estimates",
                  label = "Pivot estimates",
                  value = TRUE
                ),
                position = "right"
              ),
              DT::DTOutput("sequence_ratios_tidy") |>
                shinycssloaders::withSpinner()
            )
          )
        ),
        bslib::nav_panel(
          title = "Table",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "sequence_ratios_table_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "sequence_ratios_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                sortable::bucket_list(
                  header = NULL,
                  sortable::add_rank_list(
                    text = "None",
                    labels = c("cdm_name", "index_cohort_name", "marker_cohort_name", "cdm_name", "cohort_date_range", "combination_window", "confidence_interval", "days_prior_observation", "index_marker_gap", "moving_average_restriction", "washout_window", "variable_name", "variable_level", "estimate_name"),
                    input_id = "sequence_ratios_table_none"
                  ),
                  sortable::add_rank_list(
                    text = "Header",
                    labels = character(),
                    input_id = "sequence_ratios_table_header"
                  ),
                  sortable::add_rank_list(
                    text = "Group columns",
                    labels = character(),
                    input_id = "sequence_ratios_table_group_column"
                  ),
                  sortable::add_rank_list(
                    text = "Hide",
                    labels = character(),
                    input_id = "sequence_ratios_table_hide"
                  )
                ),
                position = "right"
              ),
              gt::gt_output("sequence_ratios_table") |>
                shinycssloaders::withSpinner()
            )
          )
        ),
        bslib::nav_panel(
          title = "Plot",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "sequence_ratios_plot_download", label = "Download plot")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::materialSwitch(
                  inputId = "sequence_ratios_plot_interactive",
                  label = "Interactive",
                  value = TRUE
                ),
                shinyWidgets::pickerInput(
                  inputId = "sequence_ratios_plot_x",
                  label = "x axis",
                  choices = c("cdm_name", "index_cohort_name", "marker_cohort_name", "variable_name", "variable_level"),
                  selected = "index_cohort_name",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shinyWidgets::pickerInput(
                  inputId = "sequence_ratios_plot_facet",
                  label = "Facet",
                  choices = c("cdm_name", "index_cohort_name", "marker_cohort_name", "cohort_date_range", "combination_window", "washout_window"),
                  selected = "cdm_name",
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shinyWidgets::pickerInput(
                  inputId = "sequence_ratios_plot_colour",
                  label = "Colour",
                  choices = c("variable_name", "index_cohort_name", "marker_cohort_name", "cohort_date_range", "combination_window", "washout_window"),
                  selected = "variable_name",
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                position = "right"
              ),
              plotly::plotlyOutput("sequence_ratios_plot") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_panel(
    title = "Temporal symmetry",
    icon = shiny::icon("folder"),
    bslib::layout_sidebar(
      sidebar = bslib::sidebar(
        shinyWidgets::pickerInput(
          inputId = "temporal_symmetry_cdm_name",
          label = "CDM name",
          choices = choices$temporal_symmetry_cdm_name,
          selected = selected$temporal_symmetry_cdm_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "temporal_symmetry_index_name",
          label = "Index name",
          choices = choices$temporal_symmetry_index_name,
          selected = selected$temporal_symmetry_index_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "temporal_symmetry_marker_name",
          label = "Marker name",
          choices = choices$temporal_symmetry_marker_name,
          selected = selected$temporal_symmetry_marker_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "temporal_symmetry_variable_name",
          label = "Variable name",
          choices = choices$temporal_symmetry_variable_name,
          selected = selected$temporal_symmetry_variable_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "temporal_symmetry_estimate_name",
          label = "Estimate name",
          choices = choices$temporal_symmetry_estimate_name,
          selected = selected$temporal_symmetry_estimate_name,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "temporal_symmetry_cohort_date_range",
          label = "Cohort date range",
          choices = choices$temporal_symmetry_cohort_date_range,
          selected = selected$temporal_symmetry_cohort_date_range,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "temporal_symmetry_combination_window",
          label = "Combination window",
          choices = choices$temporal_symmetry_combination_window,
          selected = selected$temporal_symmetry_combination_window,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "temporal_symmetry_days_prior_observation",
          label = "Days prior observation",
          choices = choices$temporal_symmetry_days_prior_observation,
          selected = selected$temporal_symmetry_days_prior_observation,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "temporal_symmetry_index_marker_gap",
          label = "Index marker gap",
          choices = choices$temporal_symmetry_index_marker_gap,
          selected = selected$temporal_symmetry_index_marker_gap,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "temporal_symmetry_moving_average_restriction",
          label = "Moving average restriction",
          choices = choices$temporal_symmetry_moving_average_restriction,
          selected = selected$temporal_symmetry_moving_average_restriction,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "temporal_symmetry_timescale",
          label = "Timescale",
          choices = choices$temporal_symmetry_timescale,
          selected = selected$temporal_symmetry_timescale,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        shinyWidgets::pickerInput(
          inputId = "temporal_symmetry_washout_window",
          label = "Washout window",
          choices = choices$temporal_symmetry_washout_window,
          selected = selected$temporal_symmetry_washout_window,
          multiple = TRUE,
          options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
        ),
        position = "left"
      ),
      shiny::actionButton(
        inputId = "update_temporal_symmetry",
        label = "Update content",
        width = "200px"
      ),
      shiny::div(shiny::textOutput(outputId = "update_message_temporal_symmetry"), class = "ov_update_button"),
      bslib::navset_card_tab(
        bslib::nav_panel(
          title = "Tidy",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "temporal_symmetry_tidy_download", label = "Download csv")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::pickerInput(
                  inputId = "temporal_symmetry_tidy_columns",
                  label = "Columns",
                  choices = c("cdm_name", "index_name", "marker_name", "cohort_date_range", "combination_window", "days_prior_observation", "index_marker_gap", "moving_average_restriction", "timescale", "washout_window", "variable_name", "variable_level"),
                  selected = c("cdm_name", "index_name", "marker_name", "variable_name", "variable_level"),
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::checkboxInput(
                  inputId = "temporal_symmetry_tidy_pivot_estimates",
                  label = "Pivot estimates",
                  value = TRUE
                ),
                position = "right"
              ),
              DT::DTOutput("temporal_symmetry_tidy") |>
                shinycssloaders::withSpinner()
            )
          )
        ),
        bslib::nav_panel(
          title = "Table",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shinyWidgets::pickerInput(
                  inputId = "temporal_symmetry_table_format",
                  label = "Format",
                  choices = c("docx", "png", "pdf", "html"),
                  selected = "docx",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shiny::downloadButton(outputId = "temporal_symmetry_table_download", label = "Download table")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                sortable::bucket_list(
                  header = NULL,
                  sortable::add_rank_list(
                    text = "None",
                    labels = c("cdm_name", "index_name", "marker_name", "cohort_date_range", "combination_window", "days_prior_observation", "index_marker_gap", "moving_average_restriction", "timescale", "washout_window", "variable_name", "variable_level", "estimate_name"),
                    input_id = "temporal_symmetry_table_none"
                  ),
                  sortable::add_rank_list(
                    text = "Header",
                    labels = character(),
                    input_id = "temporal_symmetry_table_header"
                  ),
                  sortable::add_rank_list(
                    text = "Group columns",
                    labels = character(),
                    input_id = "temporal_symmetry_table_group_column"
                  ),
                  sortable::add_rank_list(
                    text = "Hide",
                    labels = character(),
                    input_id = "temporal_symmetry_table_hide"
                  )
                ),
                position = "right"
              ),
              gt::gt_output("temporal_symmetry_table") |>
                shinycssloaders::withSpinner()
            )
          )
        ),
        bslib::nav_panel(
          title = "Plot",
          bslib::card(
            full_screen = TRUE,
            bslib::card_header(
              bslib::popover(
                shiny::icon("download"),
                shiny::downloadButton(outputId = "temporal_symmetry_plot_download", label = "Download plot")
              ),
              class = "text-end"
            ),
            bslib::layout_sidebar(
              sidebar = bslib::sidebar(
                shinyWidgets::materialSwitch(
                  inputId = "temporal_symmetry_plot_interactive",
                  label = "Interactive",
                  value = TRUE
                ),
                shinyWidgets::pickerInput(
                  inputId = "temporal_symmetry_plot_x",
                  label = "x axis",
                  choices = c("cdm_name", "index_name", "marker_name", "variable_name", "variable_level"),
                  selected = "variable_level",
                  multiple = FALSE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shinyWidgets::pickerInput(
                  inputId = "temporal_symmetry_plot_facet",
                  label = "Facet",
                  choices = c("cdm_name", "index_name", "marker_name", "cohort_date_range", "combination_window", "timescale", "washout_window"),
                  selected = "cdm_name",
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                shinyWidgets::pickerInput(
                  inputId = "temporal_symmetry_plot_colour",
                  label = "Colour",
                  choices = c("variable_name", "index_name", "marker_name", "cohort_date_range", "combination_window", "timescale", "washout_window"),
                  selected = "variable_name",
                  multiple = TRUE,
                  options = list(`actions-box` = TRUE, size = 10, `selected-text-format` = "count > 3")
                ),
                position = "right"
              ),
              plotly::plotlyOutput("temporal_symmetry_plot") |>
                shinycssloaders::withSpinner()
            )
          )
        )
      )
    )
  ),
  bslib::nav_spacer(),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("download"),
      shiny::downloadButton(
        outputId = "download_raw",
        label = "Download raw data",
        icon = shiny::icon("download")
      )
    )
  ),
  bslib::nav_item(
    bslib::popover(
      shiny::icon("circle-info"),
      shiny::tags$img(
        src = "hds_logo.svg",
        class = "logo-img",
        alt = "Logo",
        height = "auto",
        width = "30%",
        style = "float:right"
      ),
      "This shiny app was generated with ",
      shiny::a(
        "OmopViewer",
        href = "https://github.com/OHDSI/OmopViewer",
        target = "_blank"
      ),
      shiny::strong("v0.4.0")
    )
  ),
  bslib::nav_item(bslib::input_dark_mode(id = "dark_mode", mode = "light"))
)
